version: "3.9"
services:
  deployer:
    image: alpine/git:latest
    container_name: deployer
    volumes:
      - app-data:/app/repo
    entrypoint: ["/bin/sh", "-c"]
    command: >
      if [ ! -f /app/repo/index.html ]; then
        echo "Cloning repo..."
        git clone -b main https://github.com/T-J-DEV/github-autopull.git /app/repo
      fi &&
      while true; do
        echo ">>> Fetching latest code..."
        cd /app/repo
        git fetch origin main
        git reset --hard FETCH_HEAD
        echo ">>> Pull complete, sleeping 30s..."
        sleep 30
      done
    restart: always

  nginx:
    image: nginx:alpine
    container_name: web
    ports:
      - "8530:80"
    volumes:
      - app-data:/usr/share/nginx/html:ro
    depends_on:
      - deployer
    restart: always

volumes:
  app-data:
