version: "3.8"
services:
  deployer:
    image: alpine/git:latest
    container_name: deployer
    volumes:
      - app-data:/app/repo
    entrypoint: ["/bin/sh", "-c"]
    command: >
      [ ! -f /app/repo/index.html ] && echo "Cloning repo..." && git clone -b main https://github.com/T-J-DEV/github-autopull.git /app/repo;
      while true; do
        echo ">>> Fetching latest code...";
        cd /app/repo;
        git fetch origin main;
        git reset --hard FETCH_HEAD;
        echo ">>> Pull complete, sleeping 30s...";
        sleep 30;
      done
    restart: always

  nginx:
    image: nginx:alpine
    container_name: web
    ports:
      - "8530:80"
    volumes:
      - app-data:/usr/share/nginx/html:ro
    depends_on:
      - deployer
    restart: always

volumes:
  app-data:
