version: "3.9"

services:
  deployer:
    image: alpine/git:latest
    container_name: deployer
    volumes:
      - app-data:/app/repo
    entrypoint: ["/bin/sh"]
    command: ["/deploy.sh"]
    restart: always

  web:
    image: nginx:alpine
    container_name: web
    ports:
      - "8181:80"
    volumes:
      - app-data:/usr/share/nginx/html:ro
    depends_on:
      - deployer
    restart: always

volumes:
  app-data:
