version: "3.9"
services:
  deployer:
    image: alpine/git:latest
    container_name: deployer
    volumes:
      - app-data:/app/repo
      - ./deploy.sh:/deploy.sh:ro
    entrypoint: ["/bin/sh"]
    command: ["/deploy.sh"]

  nginx:
    image: nginx:alpine
    container_name: web
    ports:
      - "8530:80"
    volumes:
      - app-data:/usr/share/nginx/html:ro
    depends_on:
      - deployer

volumes:
  app-data:
